# Generated by Django 5.2.17 on 2026-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(db_index=True, max_length=32)),
                ('turn', models.PositiveSmallIntegerField()),
                ('election_id', models.CharField(max_length=16)),
                ('signature', models.CharField(max_length=64, unique=True)),
                ('progress', models.FloatField()),
                ('valid_votes', models.BigIntegerField()),
                ('state_points', models.JSONField(default=list)),
                ('observed', models.JSONField(default=dict)),
                ('forecast', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['office', 'turn', 'election_id', 'id'], name='dashboard_e_office_38eb08_idx')],
            },
        ),
    ]
